export { boardMoveOutReminderMail } from "./board-move-out-reminder.template";
export type { BoardMoveOutReminderMailProps } from "./board-move-out-reminder.template";
export { bookingCancellationMail } from "./booking-cancellation.template";
export type { BookingCancellationMailProps } from "./booking-cancellation.template";
export { bookingConfirmationMail } from "./booking-confirmation.template";
export type { BookingConfirmationMailProps } from "./booking-confirmation.template";
export type { BookingMailMode, BookingMailPeriod } from "./booking-period";
export { contactSubmissionMail } from "./contact-submission.template";
export type { ContactSubmissionMailProps } from "./contact-submission.template";
export { invitationMail } from "./invitation.template";
export type { InvitationMailProps } from "./invitation.template";
export { magicLinkRefusedMail } from "./magic-link-refused.template";
export type { MagicLinkRefusedMailProps } from "./magic-link-refused.template";
export { magicLinkMail } from "./magic-link.template";
export type { MagicLinkMailProps } from "./magic-link.template";
export { moveInMail } from "./move-in.template";
export type { MoveInMailProps } from "./move-in.template";
export { moveOutMail } from "./move-out.template";
export type { MoveOutMailProps } from "./move-out.template";
export { newsMail } from "./news.template";
export type { NewsMailProps } from "./news.template";
export { registerReportObligationMail } from "./register-report-obligation.template";
export type { RegisterReportObligationMailProps } from "./register-report-obligation.template";
export { smtpTestMail } from "./smtp-test.template";
export type { SmtpTestMailProps } from "./smtp-test.template";
