import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { afterAll, beforeAll, describe, expect, it } from "vitest";

import { LocalDiskStorageDriver } from "./local-disk.driver";
import { StorageError } from "./storage.driver";

let dataDir: string;
let driver: LocalDiskStorageDriver;

beforeAll(async () => {
  dataDir = await mkdtemp(path.join(tmpdir(), "openbrf-storage-"));
  driver = new LocalDiskStorageDriver(dataDir);
});

afterAll(async () => {
  await rm(dataDir, { recursive: true, force: true });
});

async function collect(
  stream: NodeJS.ReadableStream | null,
): Promise<Buffer | null> {
  if (stream === null) {
    return null;
  }
  const chunks: Buffer[] = [];
  for await (const chunk of stream) {
    chunks.push(Buffer.from(chunk));
  }
  return Buffer.concat(chunks);
}

describe("the local disk driver", () => {
  it("stores and reads back the same bytes", async () => {
    const bytes = Buffer.from([0x89, 0x50, 0x4e, 0x47]);
    await driver.put("media/2026/08/one.png", bytes);

    expect(await collect(await driver.open("media/2026/08/one.png"))).toEqual(
      bytes,
    );
  });

  it("writes under an uploads directory inside the data volume", async () => {
    await driver.put("media/2026/08/two.png", Buffer.from("x"));

    // Stated as a path assertion because the layout is a promise to the
    // operator: one data volume holds uploads, keys, plugins and themes, and
    // backing it up has to be backing up all four.
    expect(
      await readFile(path.join(dataDir, "uploads", "media/2026/08/two.png")),
    ).toEqual(Buffer.from("x"));
  });

  it("replaces an object that is already at the key", async () => {
    await driver.put("media/2026/08/three.png", Buffer.from("a"));
    await driver.put("media/2026/08/three.png", Buffer.from("bb"));

    expect(await collect(await driver.open("media/2026/08/three.png"))).toEqual(
      Buffer.from("bb"),
    );
  });

  it("reports a key that is not there as null rather than as a failure", async () => {
    expect(await driver.open("media/2026/08/absent.png")).toBeNull();
  });

  it("treats removing something that is not there as done", async () => {
    await expect(
      driver.remove("media/2026/08/absent.png"),
    ).resolves.toBeUndefined();
  });

  it("removes what it stored", async () => {
    await driver.put("media/2026/08/four.png", Buffer.from("x"));
    await driver.remove("media/2026/08/four.png");

    expect(await driver.open("media/2026/08/four.png")).toBeNull();
  });

  it("refuses a key that would escape the uploads directory", async () => {
    /*
     * Keys are generated by the application and cannot contain a traversal, so
     * this case is about what happens if that ever stops being true. The
     * encryption key lives on the same volume, one directory across.
     */
    await expect(
      driver.put("../keys/encryption.key", Buffer.from("x")),
    ).rejects.toThrow(StorageError);

    await expect(driver.open("../../etc/passwd")).rejects.toThrow(StorageError);
  });

  it("does not serve a half-written file", async () => {
    /*
     * The staging file is an implementation detail with a visible
     * consequence: a reader arriving mid-write must find the whole file or
     * nothing, never a prefix. Its presence next to the target is what proves
     * the write does not happen in place.
     */
    const target = path.join(dataDir, "uploads", "media/2026/08/five.png");
    await driver.put("media/2026/08/five.png", Buffer.from("x"));
    await writeFile(`${target}.leftover.part`, "partial");

    await driver.put("media/2026/08/five.png", Buffer.from("yy"));

    expect(await collect(await driver.open("media/2026/08/five.png"))).toEqual(
      Buffer.from("yy"),
    );
  });
});
