import { randomUUID } from "node:crypto";
import { createReadStream } from "node:fs";
import { mkdir, rename, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import type { Readable } from "node:stream";

import { StorageError, type StorageDriver } from "./storage.driver";

/** Whether a rejected file operation is Node's "no such file". */
function isMissing(error: unknown): boolean {
  return (
    typeof error === "object" &&
    error !== null &&
    (error as NodeJS.ErrnoException).code === "ENOENT"
  );
}

/**
 * Files on the instance's own data volume.
 *
 * The default, and the one a housing cooperative running a single container
 * needs: uploads sit next to the encryption key and the installed plugins under
 * OPENBRF_DATA_DIR, so one volume is the whole backup surface alongside the
 * database.
 */
export class LocalDiskStorageDriver implements StorageDriver {
  readonly kind = "local" as const;

  /** Absolute, so every later comparison is against a resolved path. */
  private readonly root: string;

  constructor(dataDir: string) {
    this.root = path.resolve(dataDir, "uploads");
  }

  /**
   * The content type is not a parameter here.
   *
   * A file system has nowhere to record it, and the serving path does not ask
   * storage what a file is: the type is identified from the bytes at upload and
   * kept on the file's own row. Accepting the argument and discarding it would
   * suggest otherwise.
   */
  async put(key: string, body: Buffer): Promise<void> {
    const target = this.pathFor(key);
    await mkdir(path.dirname(target), { recursive: true });

    /*
     * Written beside the target and moved into place, because a reader can
     * arrive between the create and the last write. rename is atomic within a
     * directory, so a request either finds the whole file or does not find it.
     */
    const staging = `${target}.${randomUUID()}.part`;
    try {
      await writeFile(staging, body, { flag: "wx" });
      await rename(staging, target);
    } catch (cause) {
      await rm(staging, { force: true });
      throw new StorageError(
        `Could not write ${key} to the data volume.`,
        this.kind,
        { cause },
      );
    }
  }

  // Async so that a refused key rejects rather than throwing synchronously:
  // a method declared to return a promise must not do both.
  async open(key: string): Promise<Readable | null> {
    const target = this.pathFor(key);

    return new Promise<Readable | null>((resolve, reject) => {
      const stream = createReadStream(target);
      /*
       * Resolved on the first readable event rather than returned outright, so
       * a missing file is a null here instead of an error emitted later on a
       * stream the caller has already begun piping into a response.
       */
      stream.once("open", () => {
        resolve(stream);
      });
      stream.once("error", (error: unknown) => {
        stream.destroy();
        if (isMissing(error)) {
          resolve(null);
          return;
        }
        reject(
          new StorageError(
            `Could not read ${key} from the data volume.`,
            this.kind,
            { cause: error },
          ),
        );
      });
    });
  }

  async remove(key: string): Promise<void> {
    await rm(this.pathFor(key), { force: true });
  }

  /**
   * The absolute path a key names, or a refusal.
   *
   * Keys are generated by this application and cannot contain a traversal, so
   * this check should never fire. It is here because "should never" is not a
   * security control: the cost of being wrong once is the storage layer reading
   * or overwriting an arbitrary file on the volume, including the encryption
   * key that sits next to it.
   */
  private pathFor(key: string): string {
    const resolved = path.resolve(this.root, key);
    if (resolved !== this.root && !resolved.startsWith(this.root + path.sep)) {
      throw new StorageError(
        "A storage key resolved outside the uploads directory.",
        this.kind,
      );
    }
    return resolved;
  }
}
