import type { Readable } from "node:stream";

/**
 * Where the bytes of an uploaded file live.
 *
 * One interface, so the rest of the application never learns whether a file is
 * on a disk or in a bucket. That is what keeps the serving path honest: a
 * driver hands back a stream and nothing else, so there is no shape in which a
 * driver could return a URL for the browser to follow. Files reach a visitor
 * through this instance or not at all.
 *
 * Keys are opaque, generated by the caller (see storage-key.ts) and never taken
 * from a client, so a driver may assume a key is safe to use as a path segment
 * and must still refuse one that escapes its root.
 */
export interface StorageDriver {
  /** Named in logs and in the health output, never in a response. */
  readonly kind: "local" | "s3";

  /**
   * Writes an object, replacing anything already at the key.
   *
   * Takes the whole body rather than a stream: an upload is bounded by the
   * configured limit and has to be read in full before it is stored anyway, so
   * that its bytes can be identified and its size checked. A streaming write
   * would have to store first and validate afterwards.
   */
  put(key: string, body: Buffer, contentType: string): Promise<void>;

  /**
   * Opens an object for reading, or null when there is nothing at the key.
   *
   * A stream rather than a buffer, because this is the serving path: an
   * instance that read every requested file into memory would hold one copy per
   * concurrent request.
   */
  open(key: string): Promise<Readable | null>;

  /** Removes an object. Succeeds when there was nothing to remove. */
  remove(key: string): Promise<void>;
}

/** A storage backend that could not do what it was asked. */
export class StorageError extends Error {
  constructor(
    message: string,
    readonly kind: StorageDriver["kind"],
    options?: { cause?: unknown },
  ) {
    super(message, options);
    this.name = "StorageError";
  }
}
