-- Which person each row of an import was written to.
--
-- The apply plans one chunk at a time, and a chunk's within-file matching only
-- knew the rows of that chunk. A person listed in two chunks under a key the
-- register cannot match on - a name in an apartment they have since left, with
-- no date in the row - was shown by the preview as one person and created
-- twice by the apply, each copy with its own member register ENTRY. Each chunk
-- records the rows it wrote, and the next one reads them back.
--
-- Row numbers and person ids only: nothing in it is personal data on its own.
ALTER TABLE "import_session" ADD COLUMN "rowPersons" JSONB;
